### ISSUE TITLE
Better details about parsing errors

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [common-workflow-language/cwlviewer#115]
My CWL workflow (a pretty simple one, I think: https://github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/blob/develop/zip_and_index_vcf.cwl) failed with parsing error:

> Error: The workflow could not be parsed from the given URL

This doesn't give much explanation as to what the parsing error was or how to fix it. A little more detail would be nice.

Also, if I give it the URL to a CommandLineTool, it fails with a parsing error. I didn't really expect a diagram from a Tool, but I think a message saying "This viewer only accepts URLs for Workflows" would have made this type of error more clear.

**Comment by MarkRobbo** [comment]
Currently, inline `run` parameters are not supported, and that will be the cause of this error.

I agree that the error reporting is not helpful. In the works is an update for using cwltool for parsing (see the `cwltool` branch) instead of our own implementation, which will make things more robust and have the error reporting provided where it fails. Command line tools also give a helpful error message.

**Comment by stain** [comment]
BTW, you can test the new parser output at http://view.commonwl.org:8082/ which runs the new `cwltool` branch and gives output if `cwltool` validation fails - in your case there is actually no problem anymore as the new branch does not need to do its own `run` loading.

**Comment by MarkRobbo** [comment]
There was also a couple of recently patched bugs which also managed to be caught by this particular workflow, but are now resolved on said branch
