### ISSUE TITLE
Support for git submodules.

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [common-workflow-language/cwlviewer#142]
Now that I can see the parsing errors from some of my workflows, I realize that some of my workflows failed to visualize probably because they rely on files in submodules. See: https://github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools

Some of my CWL files reference other files in Variantbam-for-dockstore and sga-annotate-docker. These are submodule references to other repositories. Would it be possible to support looking up files in submodules?

PS. I only discovered this was a problem once I saw that this issue (https://github.com/common-workflow-language/cwlviewer/issues/115) was closed and I could get detailed parsing errors. Thanks for fixing 115! :)

**Comment by MarkRobbo** [comment]
- [ ] Investigate why submodules are not being cloned despite appropriate JGit option being set
- [ ] Improve error handling to give a friendly message with `org.eclipse.jgit.api.errors.TransportException` being thrown due to lack of ssh key

**Comment by MarkRobbo** [comment]
Update on this: The problem is that there are no known_hosts on the server. This causes an exception to be thrown because [Java Secure Channel](http://www.jcraft.com/jsch/) defaults to strict host checking.

`JSchException: UnknownHostKey: github.com. RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48`

Solutions to this include:
* Don't support SSH at all for any submodule in the repository
* Add popular sites to the known_hosts file with Docker Compose

Either way a specific error message needs to be added for this situation.

**Comment by MarkRobbo** [comment]
We have decided on balance to disallow ssh for submodules for reproduciblity reasons: this same problem is inherited by someone else who is trying to clone the workflow to use it.

It would be possible to manipulate the submodule URL in `.gitmodules` but this is not ideal due to needing to be done recursively, changing the original intent and not addressing the reproducibility aspect.

This will need to be documented under 'limitations' in the about page, that `https://` URLs are required for submodules and ssh protocols are not supported in general.

**Comment by SolomonShorser-OICR** [comment]
Was the JGit issue with non-SSH submodules resolved?

**Comment by MarkRobbo** [comment]
@SolomonShorser-OICR It still works as intended when all submodules in a repository are https:// as far as I can tell.

Quick test: https://view.commonwl.org/workflows/github.com/MarkRobbo/subworkflow-test/blob/master/NF_Hello/wf.cwl

**Comment by SolomonShorser-OICR** [comment]
@MarkRobbo This subworkflow referencing a submodule now works: https://view.commonwl.org/workflows/github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/blob/develop/oxog_sub_wf.cwl

This one does not: https://view.commonwl.org/workflows/github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/blob/develop/annotator_sub_wf.cwl#

I checked and  the .gitmodules  file is updated so that both submodule references are included via https rather than ssh.

Of course the Annotator is in a separate github organization, the other submodule and the main workflow are both in the same organization, I'm not sure if that makes a difference.

**Comment by MarkRobbo** [comment]
@SolomonShorser-OICR Hmm. That shouldn't make a difference, however this may be a bug in changing the submodules after initially checking out the repository - as it works locally. I will try to investigate when I get chance

**Comment by MarkRobbo** [comment]
@SolomonShorser-OICR #152 for tracking submodule issues I've picked up
