### ISSUE TITLE
What is the license of an image generated by this code?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#183]
Apache 2.0, or something else?

Is linking to the URL for the workflow under view.commonwl.org sufficient attribution?

**Comment by tom-tan** [comment]
I guess the generated image is licensed by the owner of the original CWL.

The following link is the case of GPL but it can be applicable to other licenses.
https://www.gnu.org/licenses/gpl-faq.html.en#GPLOutput

**Comment by stain** [comment]
Yes, it would be derived from the original workflow, so that license would apply. Currently we just do a cheeky _"Shown workflow has separate copyright and license."_ and link back to GitHub.

Perhaps the real issue is to expose the `schema:license` annotation and give a warning if license is unknown.
