### ISSUE TITLE
No information shown if non-packed workflow uses id  field

### ISSUE THREAD

**Issue by byb121** [common-workflow-language/cwlviewer#228]
## Description
I tried to visualize this workflow using the online CWL viewer:

https://github.com/cancerit/cgpRna/blob/177d01c89c1d8d3f2fe09532c8118f4c35e49f4e/cwls/infuse_pipeline.cwl

## Expected Behavior

Render a graph like this:

![Screen Shot 2019-11-06 at 11 55 32](https://user-images.githubusercontent.com/3796450/68296374-6057a700-008c-11ea-9520-4033e6e4fbb1.png)

## Actual Behavior

It does not show any graph or error:
![Screen Shot 2019-11-06 at 11 48 35](https://user-images.githubusercontent.com/3796450/68296286-2ededb80-008c-11ea-9aaa-b99c4cc63f7d.png)

## Your Environment

* Google Chrome: Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by stain** [comment]
I think this might be same bug as #226 - can you try commenting out the workflow's `id` field?

**Comment by byb121** [comment]
It seems cwl viewer site is down. I'll have a go when it's back.

**Comment by byb121** [comment]
@stain Yes, you're right, removing id field works. Happy to be merged into that issue if it helps.

**Comment by stain** [comment]
I am not sure why it happens..  Basically there is some logic that checks if it is a packed workflow, in which case a dialogue pops up to [select](https://view.commonwl.org/workflows/github.com/mr-c/cwltests/blob/pack_test/cwl/packed.cwl) the workflow by `id` - having a corresponding sub-resource but using `%23` to escape the character `#` (which is not transmitted over HTTP) - e.g. <https://view.commonwl.org/workflows/github.com/mr-c/cwltests/blob/pack_test/cwl/packed.cwl%23main>

In its [turtle](https://w3id.org/cwl/view/git/97d571496beb2411121f764c92e3b18de34396fe/cwl/packed.cwl?part=main&format=turtle) we then find:

```turtle
<https://w3id.org/cwl/view/git/97d571496beb2411121f764c92e3b18de34396fe/cwl/packed.cwl#main>
        a                 cwl:Workflow ;
``` 

as well as of course the other nested workflows:

```turtle
<https://w3id.org/cwl/view/git/97d571496beb2411121f764c92e3b18de34396fe/cwl/packed.cwl#workflow_sig.cwl>
        a                 cwl:Workflow ;
```

Now "simple case" of not being a packed workflow, if there is no `id` then the Turtle from the workflow will just use the filename as the identifier for the workflow. For instance for [lobstr](https://w3id.org/cwl/view/git/17b65ea19d81527090fded62ffa0e1ba3b25d561/workflows/lobSTR/lobSTR-workflow.cwl?format=turtle)

```turtle
<https://w3id.org/cwl/view/git/17b65ea19d81527090fded62ffa0e1ba3b25d561/workflows/lobSTR/lobSTR-workflow.cwl>
        a               cwl:Workflow ;
```

However if there is only one workflow, then that `%23` mechanism does not seem to be active, while it may needs to be there to pick up the (only) `Workflow` identifier, because if I look in the [turtle](https://w3id.org/cwl/view/git/177d01c89c1d8d3f2fe09532c8118f4c35e49f4e/cwls/infuse_pipeline.cwl?format=turtle) I find (way down)

```turtle
<https://w3id.org/cwl/view/git/177d01c89c1d8d3f2fe09532c8118f4c35e49f4e/cwls/infuse_pipeline.cwl#multi-lane-cgprna-with-infuse-workflow>
        a                        cwl:Workflow ;
```

So I think the code assumes if it's not packed, then there is no `id`. I am trying to dig out where in the code base this is.

**Comment by stain** [comment]
[suspected codeline found](https://github.com/common-workflow-language/cwlviewer/blob/12ecbb131a9c0f710a57e74194171e5814e12e31/src/main/java/org/commonwl/view/workflow/WorkflowController.java#L497)

**Comment by mr-c** [comment]
This issue seems to be fixed
