### ISSUE TITLE
replace mongodb with a F/OSS database

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#254]
mongodb is no long F/OSS as of October 2018 https://en.wikipedia.org/wiki/MongoDB#MongoDB_Community_Server_2

Preferably something already packaged for Debian

Candidates include
- PostgreSQL
  [The Guardian migrated from MongoDB to PostgreSQL in 2018](https://www.theguardian.com/info/2018/nov/30/bye-bye-mongo-hello-postgres) using the [`JSONB` type](https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/)

**Comment by stain** [comment]
Agree that we should move away. For now we are still using mongodb 3.4 which is AGPL.

```
root@16776f26e336:/usr/share/doc/mongodb-org-server# ls
GNU-AGPL-3.0.gz  MPL-2.gz  README  THIRD-PARTY-NOTICES.gotools.gz  THIRD-PARTY-NOTICES.gz  changelog.gz  copyright
```

That said I am not fully certain if we are fully complying with [Affero GPL](https://www.gnu.org/licenses/agpl-3.0.en.html) at the moment - although we are providing links to this source code we don't provide links to the MongoDB source code?

**Comment by obasekiosa** [comment]
Is [Cassandra](https://cassandra.apache.org/) also a viable choice for the replacement?

Its license is the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0).
Also, moving nested schema would be straightforward without the need for foreign keys and separate tables for workflows that are in the queued object.

**Comment by mr-c** [comment]
> a viable choice for the replacement?

We should make a list of characteristics we want in a replacement database and then evaluate our options. Could you compile a list of characteristics?

Looks like https://www.google.com/search?q=how+to+decide+on+a+new+database+engine returns some useful results to consider.

**Comment by tetron** [comment]
@obasekiosa would you be able to look at the code and write down how `cwlviewer` uses the database right now?

I would strongly learn towards Postgres but we should consider all the options.

**Comment by obasekiosa** [comment]
Oh great. 
While currently after much digging, I am all for Postgres.
This is what I was able to compile on both options.

[Postgres VS Cassandra](https://docs.google.com/document/d/19ilrHDyu7G5Qo1yQ-88vlyEDDnyIHPav8LVx0gLUnCk/edit?usp=sharing)

**Comment by obasekiosa** [comment]
While still on the code coverage and making progress.

I was also able to extract the Workflow and Queued Workflow schema as is in the database.
Currently modelling the Workflow on PostgreSQL - a lot of nested objects.

I also noticed that these two collections are in a database named test. Is that the name used in the production db also?

I was also able to look into the spring data implementation for PostgreSQL and how to use it.

Haven't been able to understand how to perform queries on a JSON dump in PostgreSQL hence why I began modelling just in case.

**Comment by kinow** [comment]
Will start working on it this week (probably, otherwise in the beginning of next week). What I think are the requirements for this task:

- [ ] update `pom.xml` dependencies, removing Mongo, adding Postgres + Hibernate (or data/jdbc)
- [ ] replace the Spring configuration used by Mongo, probably add one for Postgres (pool settings, etc)
- [ ] update the repositories to use Hibernate or JDBC instead of Data+Mongo
- [ ] update entities and other annotations & classes as needed
- [ ] add database migration, with initial DDL, but try to include some instructions for future DML's too
- [ ] update tests
- [ ] manual tests
- [ ] send to review and write notes about anything important to observe when migrating, any docs, etc

**Comment by kinow** [comment]
I think having PostgreSQL makes things easier to have cwlviewer distributed and used in multiple places. I am not familiar with Debian guidelines, but I worked in companies that avoided Elastic or Mongo just to not have any risk of more license changes affecting their business (even if OK for a bank for example to use it, managers are required to give detailed explanation yo upper management when choosing OSS software instead of proprietary, and these license issues/changes are not weel regarded, even when for the best)

While I think the Spring Boot integration was not factored in the decision to move to another DB, it is much easier to keep SpringBoot up to date by using JPA Data instead of the MongoDB Data library (more updates, more users, more devs familiar with.)

Bruno

**Comment by mr-c** [comment]
@fmigneault I'm a Debian Developer, so when I said "put cwlviewer in Debian" I meant "have Debian packages for cwlviewer in the main official Debian archive" :-)
