### ISSUE TITLE
Use as command line tool to generate png/svg/dot ?

### ISSUE THREAD

**Issue by astewart-twist** [common-workflow-language/cwlviewer#98]
This is a very neat tool.  Couple questions:

1. Does this have to be strictly run as a web service?  Could the container possibly be ran as a CLI?
2. Does it strictly need to input CWLs from github?  Or could they be a local file?

My use case is that it would be neat to use this as an automated build step to generate diagram from version controlled CWLs (via jenkins or travis).

**Comment by MarkRobbo** [comment]
1. Yes, this is a [Spring Boot](https://projects.spring.io/spring-boot/) MVC application and currently there is no easy way of running it as a CLI which I am aware of in its current state. It would theoretically be possible by replacing web MVC controllers with something like [Spring Shell](https://projects.spring.io/spring-shell/) but requires some work

2. Currently yes the functionality is tied into downloading workflows from Github. This could be changed in future to use an abstract interface in order to use other methods for downloading files and getting metadata - and is a priority feature

---

That is a very neat use case and something I would very much like to support. The easiest way I can think of doing it currently would if you are using Github would be to to go to:

```
https://view.commonwl.org/workflow/<githubURL>
```

and grab the svg off the page, but this is obviously not ideal as consideration was not given to this kind of usage in development.

**Comment by alexbarrera** [comment]
@MarkRobbo The viewer is looking really good! I'm also interested in the use case described here. Are there any plans on having an option to bypass the cache (e.g. --no-cache) or rewrite a diagram (e.g. --force)?

**Comment by MarkRobbo** [comment]
@alexbarrera sorry for the late response on this

If you are running your own instance you can set the cache time to 0 in the configuration currently. Plans are also underway to make caching less of a pain, currently the system is far from ideal for people still developing their workflows

**Comment by alexbarrera** [comment]
@MarkRobbo Sounds good, thanks Mark!

**Comment by MarkRobbo** [comment]
Work is underway to provide a RESTful API which will hopefully fill the same need for those with public workflows. This will be merged with cwltool verification functionality

**Comment by MarkRobbo** [comment]
Draft API: http://view.commonwl.org:8082/apidocs
